### ISSUE TITLE
Class missing

### ISSUE THREAD

**Issue by bb-git** [innovian/HVTableView#22] opened 2016-11-18 18:04 UTC
So was it your plan to remove the code? HVTableView is empty after pod install.

**Comment by luomuwen** [comment] 2017-03-22 02:24
the same question

**Comment by bb-git** [comment] 2017-03-22 02:36
The project is dead, take the files from the example and include them directly. You only need HVTableView.h and .m
But be aware of the open issues, none of them got fixed.

**Comment by xerxes235** [comment] 2017-06-23 15:00
the issue is resolved in 0.2.0 version. Sorry for the inconvenience. 
If you are using pods do this:
pod update

thanks.

**Closed by xerxes235** 2017-06-23 15:00 UTC
